kind: Service
apiVersion: v1
metadata:
  name: weather-api-svc
spec:
  selector:
    name: weather-api
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      # nodePort: 30802