name: Build & Push Image

on:
  push:
    branches:
      - dev
      - main
jobs:
  build-api-image-push-to-acr:
    uses: ./.github/workflows/build-dev-image.yml
    secrets:
      DEV_ACR_SP_ID: ${{ secrets.DEV_ACR_SP_ID }}
      DEV_ACR_SP_PASSWORD: ${{ secrets.DEV_ACR_SP_PASSWORD }}
  deploy-infra-with-terraform:
    needs: [build-api-image-push-to-acr]
    uses: ./.github/workflows/terraform-apply.yml
    secrets:
      DEV_STORAGE_ACCOUNT_NAME: ${{ secrets.DEV_STORAGE_ACCOUNT_NAME }}
      DEV_STORAGE_CONTAINER_NAME: ${{ secrets.DEV_STORAGE_CONTAINER_NAME }}
      DEV_STORAGE_ACCESS_KEY: ${{ secrets.DEV_STORAGE_ACCESS_KEY }}
      DEV_ARM_CLIENT_ID: ${{ secrets.DEV_ARM_CLIENT_ID }}
      DEV_ARM_CLIENT_SECRET: ${{ secrets.DEV_ARM_CLIENT_SECRET }}
      DEV_ARM_TENANT_ID: ${{ secrets.DEV_ARM_TENANT_ID }}
      DEV_ARM_SUBSCRIPTION_ID: ${{ secrets.DEV_ARM_SUBSCRIPTION_ID }}
      DEV_PSQL_ADMIN_LOGIN: ${{ secrets.DEV_PSQL_ADMIN_LOGIN }} 
      DEV_PSQL_ADMINISTRATOR_LOGIN_PASSWORD: ${{ secrets.DEV_PSQL_ADMINISTRATOR_LOGIN_PASSWORD }} 
  deploy-app-in-k8s:
    needs: [deploy-infra-with-terraform]
    uses: ./.github/workflows/k8s-deploy.yml
    secrets:
      DEV_ACR_SP_ID: ${{ secrets.DEV_ACR_SP_ID }}
      DEV_ACR_SP_PASSWORD: ${{ secrets.DEV_ACR_SP_PASSWORD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}